### PR TITLE
accuracy about crystax port

### PR DESCRIPTION
**Pull request by pmp-p**
sitot dit sitot fait

### CODE REVIEW

**Comment by vstinner** [comment]
"Python 2.7 and 3.5 can be used on Android using CrystaX NDK. It uses patches on Python."

Is this sentence wrong?

**Comment by pmp-p** [comment]
yes, also 3.6 can build fine when built and linked to crystax

**Comment by vstinner** [comment]
Please update your PR to fix also the first sentence in that case.

**Comment by vstinner** [comment]
Outdated.

**Pull request closed without merging**
